# This is a config for E2B sandbox template.
# You can use template ID (elyrd6rz3i6jgjphuwdo) or template name (zync) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("zync") # Sync sandbox
# sandbox = await AsyncSandbox.create("zync") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zync')

team_id = "759d64d5-dff1-4079-897b-312c786956b9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "zync"
template_id = "elyrd6rz3i6jgjphuwdo"
