# This is a config for E2B sandbox template.
# You can use template ID (7chhho7dy3qy7cnu5vq0) or template name (zyncreacted) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("zyncreacted") # Sync sandbox
# sandbox = await AsyncSandbox.create("zyncreacted") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('zyncreacted')

team_id = "759d64d5-dff1-4079-897b-312c786956b9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "zyncreacted"
template_id = "7chhho7dy3qy7cnu5vq0"
